/**
 * Represents an active model available in the AI Horde.
 * Based on the API response from /v2/status/models
 */
export interface ActiveModel {
  /** The name of the model. */
  name: string;
  /** How many workers are running this model. */
  count: number;
  /** The average speed of generation for this model. */
  performance?: number;
  /** The amount waiting to be generated by this model. */
  queued?: number;
  /** The job count waiting to be generated by this model. */
  jobs?: number;
  /** Estimated time in seconds for this model's queue to be cleared. */
  eta?: number;
  /** The model type (text or image). */
  type?: 'image' | 'text';
}

/** Type of model: image or text */
export type ModelType = 'image' | 'text';
